on:
  push:
    branches: 
      - '*'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Run tests
        run: |
          sudo apt-get update -y
          sudo apt-get install -y bats
          bats ./test/test.bats